apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: manager-priority-class
  labels: {}
value: 2000000
globalDefault: false
description: "Scheduling priority of the NATS-Manager module. Must not be blocked by unschedulable user workloads."
