---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.1
  name: nats.operator.kyma-project.io
spec:
  group: operator.kyma-project.io
  names:
    categories:
    - kyma-modules
    - kyma-nats
    kind: NATS
    listKind: NATSList
    plural: nats
    singular: nats
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: State of NATS deployment
      jsonPath: .status.state
      name: State
      type: string
    - description: Age of the resource
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: NATS is the Schema for the NATS API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            default:
              cluster:
                size: 3
              jetStream:
                fileStorage:
                  size: 1Gi
                  storageClassName: default
                memStorage:
                  enabled: true
                  size: 1Gi
              logging:
                debug: false
                trace: false
              resources:
                limits:
                  cpu: 500m
                  memory: 1Gi
                requests:
                  cpu: 40m
                  memory: 64Mi
            description: Defines the desired state of NATS.
            properties:
              annotations:
                additionalProperties:
                  type: string
                description: Allows to add annotations to NATS.
                type: object
              cluster:
                default:
                  size: 3
                description: Defines configurations that are specific to NATS
                  clusters.
                properties:
                  size:
                    default: 3
                    description: Size of a NATS cluster, such as, number of NATS nodes.
                    minimum: 1
                    type: integer
                    x-kubernetes-validations:
                    - message: size only accepts odd numbers
                      rule: (self%2) != 0
                    - message: cannot be set to 1 if size was greater than 1
                      rule: '!(oldSelf > 1 && self == 1)'
                type: object
              jetStream:
                default:
                  fileStorage:
                    size: 1Gi
                    storageClassName: default
                  memStorage:
                    enabled: true
                    size: 1Gi
                description: Defines configurations that are specific to
                  NATS JetStream.
                properties:
                  fileStorage:
                    default:
                      size: 1Gi
                      storageClassName: default
                    description: Defines configurations to file storage
                      in NATS JetStream.
                    properties:
                      size:
                        anyOf:
                        - type: integer
                        - type: string
                        default: 1Gi
                        description: Defines the file storage size.
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                        x-kubernetes-validations:
                        - message: fileStorage is immutable once it was set
                          rule: self == oldSelf
                      storageClassName:
                        default: default
                        description: Defines the file storage class.
                          name.
                        type: string
                        x-kubernetes-validations:
                        - message: fileStorage is immutable once it was set
                          rule: self == oldSelf
                    type: object
                    x-kubernetes-validations:
                    - message: fileStorage is immutable once it was set
                      rule: self == oldSelf
                  memStorage:
                    default:
                      enabled: true
                      size: 1Gi
                    description: Defines configurations to memory storage
                      in NATS JetStream.
                    properties:
                      enabled:
                        default: true
                        description: Enabled allows the enablement of memory storage.
                        type: boolean
                      size:
                        anyOf:
                        - type: integer
                        - type: string
                        default: 1Gi
                        description: Defines the memory storage size.
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                    type: object
                    x-kubernetes-validations:
                    - message: can only be enabled if size is not 0
                      rule: '!self.enabled || self.size != 0'
                type: object
                x-kubernetes-validations:
                - message: fileStorage is immutable once it was set
                  rule: self.fileStorage == oldSelf.fileStorage
              labels:
                additionalProperties:
                  type: string
                description: Allows you to add labels to NATS.
                type: object
              logging:
                default:
                  debug: false
                  trace: false
                description: Defines configurations that are specific to
                  NATS logging in NATS.
                properties:
                  debug:
                    default: false
                    description: Allows you to debug logging.
                    type: boolean
                  trace:
                    default: false
                    description: Allows you to trace logging.
                    type: boolean
                type: object
              resources:
                default:
                  limits:
                    cpu: 500m
                    memory: 1Gi
                  requests:
                    cpu: 40m
                    memory: 64Mi
                description: Defines resources for NATS.
                properties:
                  claims:
                    description: Lists the resources used by this container.
                      This is an alpha field and requires enabling the
                      DynamicResourceAllocation feature gate.
                      This field is immutable. It can only be set for containers.
                    items:
                      description: ResourceClaim references one entry in PodSpec.ResourceClaims.
                      properties:
                        name:
                          description: The name must match the name of one entry in **pod.spec.resourceClaims** of
                            the Pod where this field is used. It makes that resource available
                            inside a container.
                          type: string
                        request:
                          description: The name chosen for a request in the referenced claim.
                            If empty, everything from the claim is made available; otherwise,
                            only the result of this request.
                          type: string
                      required:
                      - name
                      type: object
                    type: array
                    x-kubernetes-list-map-keys:
                    - name
                    x-kubernetes-list-type: map
                  limits:
                    additionalProperties:
                      anyOf:
                      - type: integer
                      - type: string
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                    description: Describes the maximum amount of compute resources allowed.
                      See also https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/.
                    type: object
                  requests:
                    additionalProperties:
                      anyOf:
                      - type: integer
                      - type: string
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                    description: Describes the minimum amount of compute resources required.
                      If Requests is omitted for a container, it defaults to Limits if that is explicitly specified,
                      otherwise to an implementation-defined value. Requests cannot exceed Limits.
                      See also https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/.
                    type: object
                type: object
            type: object
          status:
            description: Defines the observed state of NATS.
            properties:
              availabilityZonesUsed:
                type: integer
              conditions:
                items:
                  description: Contains details for one aspect of the current
                    state of this API resource.
                  properties:
                    lastTransitionTime:
                      description: The last time the condition transitioned from one status to another.
                        This should be when the underlying condition changed. If that is not known, then using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about the transition.
                        This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: Represents the **.metadata.generation** that the condition was set based upon.
                        For instance, if **.metadata.generation** is currently 12, but the **.status.conditions[x].observedGeneration** is 9, the condition is out of date
                        with respect to the current state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: Contains a programmatic identifier indicating the reason for the condition's last transition.
                        Producers of specific condition types may define expected values and meanings for this field,
                        and whether the values are considered a guaranteed API.
                        The value should be a CamelCase string.
                        This field may not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: The status of the condition. Either `True`, `False`, or `Unknown`.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: The type of the condition in CamelCase or in foo.example.com/CamelCase.
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              state:
                type: string
              url:
                type: string
            required:
            - state
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
