name: e2e

env:
  DOCKER_IMAGE: europe-docker.pkg.dev/kyma-project/dev/nats-manager:PR-${{ github.event.number }}

on:
  pull_request:
    branches: [ "main" ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup a k3d cluster
        uses: nolar/setup-k3d-k3s@v1
        with:
          # This is the Kubernetes version used by k3d. See https://kubernetes.io/releases/
          version: v1.26.5
      -
        name: Install the NATS CRD on the cluster
        run: |
          make install
      -
        name: Wait for the 'pull-nats-manager-build' job to succeed
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          running-workflow-name: 'pull-nats-manager-build'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success
          verbose: false # change for debugging
      -
        name: Deploy the controller to the cluster
        run: |
          make deploy IMG=$DOCKER_IMAGE
      -
        name: Test
        run: |
          go test ./e2e/... --tags=e2e
      -
        name: List namespaces, statefulSets, CRDs and Pods
        run: |
          kubectl get namespaces
          kubectl get sts --all-namespaces
          kubectl get crd --all-namespaces
          kubectl get pods --all-namespaces
      -
        name: run NATS bench
        run: |
          go install github.com/nats-io/natscli/nats@latest
          kubectl -n kyma-system port-forward svc/eventing-nats 4222:4222 &
          sleep 1
          # The following will run `bench` with the subject 'testsubject', 5 publishers 5 subscribers, 
          # 16 byte size per message, 1000 messages using JetStream.
          $HOME/go/bin/nats bench testsubject --pub 5 --sub 5 --size 16 --msgs 1000 --js

# references:
# wait for other gh checks to finish: https://github.com/marketplace/actions/wait-for-check